//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMarket.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntradayQuote
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public long UTCEpochMs { get; set; }
        public Nullable<System.DateTime> UTCDateTime { get; set; }
        public Nullable<System.DateTime> LocalDateTime { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
