-- Skip the database creation if we're not on the correct machine.
IF (@@SERVERNAME = 'DEV-SQL\ITSSQL')
BEGIN
	IF NOT EXISTS (SELECT * FROM master.dbo.sysdatabases WHERE [name] = 'SMAData')
	BEGIN
		PRINT 'Creating "SMAData" database"..'

		CREATE DATABASE [SMAData]
		 CONTAINMENT = NONE
		 ON  PRIMARY 
		( NAME = N'SMAData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.ITSSQL\MSSQL\DATA\SMAData.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
		 LOG ON 
		( NAME = N'SMAData_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.ITSSQL\MSSQL\DATA\SMAData_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
		ALTER DATABASE [SMAData] SET COMPATIBILITY_LEVEL = 120
		
		IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
		begin
			EXEC [SMAData].[dbo].[sp_fulltext_database] @action = 'enable'
		end
		
		ALTER DATABASE [SMAData] SET ANSI_NULL_DEFAULT OFF 
		ALTER DATABASE [SMAData] SET ANSI_NULLS OFF 
		ALTER DATABASE [SMAData] SET ANSI_PADDING OFF 
		ALTER DATABASE [SMAData] SET ANSI_WARNINGS OFF 
		ALTER DATABASE [SMAData] SET ARITHABORT OFF 
		ALTER DATABASE [SMAData] SET AUTO_CLOSE OFF 
		ALTER DATABASE [SMAData] SET AUTO_SHRINK OFF 
		ALTER DATABASE [SMAData] SET AUTO_UPDATE_STATISTICS ON 
		ALTER DATABASE [SMAData] SET CURSOR_CLOSE_ON_COMMIT OFF 
		ALTER DATABASE [SMAData] SET CURSOR_DEFAULT  GLOBAL 
		ALTER DATABASE [SMAData] SET CONCAT_NULL_YIELDS_NULL OFF 
		ALTER DATABASE [SMAData] SET NUMERIC_ROUNDABORT OFF 
		ALTER DATABASE [SMAData] SET QUOTED_IDENTIFIER OFF 
		ALTER DATABASE [SMAData] SET RECURSIVE_TRIGGERS OFF 
		ALTER DATABASE [SMAData] SET  DISABLE_BROKER 
		ALTER DATABASE [SMAData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
		ALTER DATABASE [SMAData] SET DATE_CORRELATION_OPTIMIZATION OFF 
		ALTER DATABASE [SMAData] SET TRUSTWORTHY OFF 
		ALTER DATABASE [SMAData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
		ALTER DATABASE [SMAData] SET PARAMETERIZATION SIMPLE 
		ALTER DATABASE [SMAData] SET READ_COMMITTED_SNAPSHOT OFF 
		ALTER DATABASE [SMAData] SET HONOR_BROKER_PRIORITY OFF 
		ALTER DATABASE [SMAData] SET RECOVERY FULL 
		ALTER DATABASE [SMAData] SET  MULTI_USER 
		ALTER DATABASE [SMAData] SET PAGE_VERIFY CHECKSUM  
		ALTER DATABASE [SMAData] SET DB_CHAINING OFF 
		ALTER DATABASE [SMAData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
		ALTER DATABASE [SMAData] SET TARGET_RECOVERY_TIME = 0 SECONDS 
		ALTER DATABASE [SMAData] SET DELAYED_DURABILITY = DISABLED 
		ALTER DATABASE [SMAData] SET  READ_WRITE 
	END
	ELSE
		PRINT 'The database "SMAData" already exists..'
END
ELSE
	PRINT 'Wrong machine, skipping "SMAData" database creation..'